/*
 * Spoolman REST API v1
 *
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ZebraApp.Api.Client.OpenAPIDateConverter;

namespace ZebraApp.Api.Model
{
    /// <summary>
    /// SettingKV
    /// </summary>
    [DataContract(Name = "SettingKV")]
    public partial class SettingKV : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SettingKV" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SettingKV() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SettingKV" /> class.
        /// </summary>
        /// <param name="key">Setting key. (required).</param>
        /// <param name="setting">Setting value. (required).</param>
        public SettingKV(string key = default(string), SettingResponse setting = default(SettingResponse))
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for SettingKV and cannot be null");
            }
            this.Key = key;
            // to ensure "setting" is required (not null)
            if (setting == null)
            {
                throw new ArgumentNullException("setting is a required property for SettingKV and cannot be null");
            }
            this.Setting = setting;
        }

        /// <summary>
        /// Setting key.
        /// </summary>
        /// <value>Setting key.</value>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Setting value.
        /// </summary>
        /// <value>Setting value.</value>
        [DataMember(Name = "setting", IsRequired = true, EmitDefaultValue = true)]
        public SettingResponse Setting { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SettingKV {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Setting: ").Append(Setting).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
