/*
 * Spoolman REST API v1
 *
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using ZebraApp.Api.Client;
using ZebraApp.Api.Model;

namespace ZebraApp.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFieldApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Add Or Update Extra Field
        /// </summary>
        /// <remarks>
        /// Add or update an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="extraFieldParameters"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExtraField&gt;</returns>
        List<ExtraField> AddOrUpdateExtraFieldFieldEntityTypeKeyPost(EntityType entityType, string key, ExtraFieldParameters extraFieldParameters, int operationIndex = 0);

        /// <summary>
        /// Add Or Update Extra Field
        /// </summary>
        /// <remarks>
        /// Add or update an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="extraFieldParameters"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExtraField&gt;</returns>
        ApiResponse<List<ExtraField>> AddOrUpdateExtraFieldFieldEntityTypeKeyPostWithHttpInfo(EntityType entityType, string key, ExtraFieldParameters extraFieldParameters, int operationIndex = 0);
        /// <summary>
        /// Delete Extra Field
        /// </summary>
        /// <remarks>
        /// Delete an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExtraField&gt;</returns>
        List<ExtraField> DeleteExtraFieldFieldEntityTypeKeyDelete(EntityType entityType, string key, int operationIndex = 0);

        /// <summary>
        /// Delete Extra Field
        /// </summary>
        /// <remarks>
        /// Delete an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExtraField&gt;</returns>
        ApiResponse<List<ExtraField>> DeleteExtraFieldFieldEntityTypeKeyDeleteWithHttpInfo(EntityType entityType, string key, int operationIndex = 0);
        /// <summary>
        /// Get Extra Fields
        /// </summary>
        /// <remarks>
        /// Get all extra fields for a specific entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExtraField&gt;</returns>
        List<ExtraField> GetExtraFieldsFieldEntityTypeGet(EntityType entityType, int operationIndex = 0);

        /// <summary>
        /// Get Extra Fields
        /// </summary>
        /// <remarks>
        /// Get all extra fields for a specific entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExtraField&gt;</returns>
        ApiResponse<List<ExtraField>> GetExtraFieldsFieldEntityTypeGetWithHttpInfo(EntityType entityType, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFieldApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Add Or Update Extra Field
        /// </summary>
        /// <remarks>
        /// Add or update an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="extraFieldParameters"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExtraField&gt;</returns>
        System.Threading.Tasks.Task<List<ExtraField>> AddOrUpdateExtraFieldFieldEntityTypeKeyPostAsync(EntityType entityType, string key, ExtraFieldParameters extraFieldParameters, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Add Or Update Extra Field
        /// </summary>
        /// <remarks>
        /// Add or update an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="extraFieldParameters"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExtraField&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ExtraField>>> AddOrUpdateExtraFieldFieldEntityTypeKeyPostWithHttpInfoAsync(EntityType entityType, string key, ExtraFieldParameters extraFieldParameters, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Delete Extra Field
        /// </summary>
        /// <remarks>
        /// Delete an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExtraField&gt;</returns>
        System.Threading.Tasks.Task<List<ExtraField>> DeleteExtraFieldFieldEntityTypeKeyDeleteAsync(EntityType entityType, string key, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Delete Extra Field
        /// </summary>
        /// <remarks>
        /// Delete an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExtraField&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ExtraField>>> DeleteExtraFieldFieldEntityTypeKeyDeleteWithHttpInfoAsync(EntityType entityType, string key, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get Extra Fields
        /// </summary>
        /// <remarks>
        /// Get all extra fields for a specific entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExtraField&gt;</returns>
        System.Threading.Tasks.Task<List<ExtraField>> GetExtraFieldsFieldEntityTypeGetAsync(EntityType entityType, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Extra Fields
        /// </summary>
        /// <remarks>
        /// Get all extra fields for a specific entity type.
        /// </remarks>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExtraField&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ExtraField>>> GetExtraFieldsFieldEntityTypeGetWithHttpInfoAsync(EntityType entityType, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFieldApi : IFieldApiSync, IFieldApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FieldApi : IFieldApi
    {
        private ZebraApp.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FieldApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FieldApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FieldApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FieldApi(string basePath)
        {
            this.Configuration = ZebraApp.Api.Client.Configuration.MergeConfigurations(
                ZebraApp.Api.Client.GlobalConfiguration.Instance,
                new ZebraApp.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new ZebraApp.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ZebraApp.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = ZebraApp.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FieldApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FieldApi(ZebraApp.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ZebraApp.Api.Client.Configuration.MergeConfigurations(
                ZebraApp.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new ZebraApp.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ZebraApp.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = ZebraApp.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FieldApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public FieldApi(ZebraApp.Api.Client.ISynchronousClient client, ZebraApp.Api.Client.IAsynchronousClient asyncClient, ZebraApp.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ZebraApp.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ZebraApp.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ZebraApp.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ZebraApp.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ZebraApp.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Add Or Update Extra Field Add or update an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="extraFieldParameters"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExtraField&gt;</returns>
        public List<ExtraField> AddOrUpdateExtraFieldFieldEntityTypeKeyPost(EntityType entityType, string key, ExtraFieldParameters extraFieldParameters, int operationIndex = 0)
        {
            ZebraApp.Api.Client.ApiResponse<List<ExtraField>> localVarResponse = AddOrUpdateExtraFieldFieldEntityTypeKeyPostWithHttpInfo(entityType, key, extraFieldParameters);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add Or Update Extra Field Add or update an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="extraFieldParameters"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExtraField&gt;</returns>
        public ZebraApp.Api.Client.ApiResponse<List<ExtraField>> AddOrUpdateExtraFieldFieldEntityTypeKeyPostWithHttpInfo(EntityType entityType, string key, ExtraFieldParameters extraFieldParameters, int operationIndex = 0)
        {
            // verify the required parameter 'key' is set
            if (key == null)
            {
                throw new ZebraApp.Api.Client.ApiException(400, "Missing required parameter 'key' when calling FieldApi->AddOrUpdateExtraFieldFieldEntityTypeKeyPost");
            }

            // verify the required parameter 'extraFieldParameters' is set
            if (extraFieldParameters == null)
            {
                throw new ZebraApp.Api.Client.ApiException(400, "Missing required parameter 'extraFieldParameters' when calling FieldApi->AddOrUpdateExtraFieldFieldEntityTypeKeyPost");
            }

            ZebraApp.Api.Client.RequestOptions localVarRequestOptions = new ZebraApp.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ZebraApp.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ZebraApp.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("entity_type", ZebraApp.Api.Client.ClientUtils.ParameterToString(entityType)); // path parameter
            localVarRequestOptions.PathParameters.Add("key", ZebraApp.Api.Client.ClientUtils.ParameterToString(key)); // path parameter
            localVarRequestOptions.Data = extraFieldParameters;

            localVarRequestOptions.Operation = "FieldApi.AddOrUpdateExtraFieldFieldEntityTypeKeyPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<List<ExtraField>>("/field/{entity_type}/{key}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddOrUpdateExtraFieldFieldEntityTypeKeyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add Or Update Extra Field Add or update an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="extraFieldParameters"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExtraField&gt;</returns>
        public async System.Threading.Tasks.Task<List<ExtraField>> AddOrUpdateExtraFieldFieldEntityTypeKeyPostAsync(EntityType entityType, string key, ExtraFieldParameters extraFieldParameters, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ZebraApp.Api.Client.ApiResponse<List<ExtraField>> localVarResponse = await AddOrUpdateExtraFieldFieldEntityTypeKeyPostWithHttpInfoAsync(entityType, key, extraFieldParameters, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add Or Update Extra Field Add or update an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="extraFieldParameters"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExtraField&gt;)</returns>
        public async System.Threading.Tasks.Task<ZebraApp.Api.Client.ApiResponse<List<ExtraField>>> AddOrUpdateExtraFieldFieldEntityTypeKeyPostWithHttpInfoAsync(EntityType entityType, string key, ExtraFieldParameters extraFieldParameters, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'key' is set
            if (key == null)
            {
                throw new ZebraApp.Api.Client.ApiException(400, "Missing required parameter 'key' when calling FieldApi->AddOrUpdateExtraFieldFieldEntityTypeKeyPost");
            }

            // verify the required parameter 'extraFieldParameters' is set
            if (extraFieldParameters == null)
            {
                throw new ZebraApp.Api.Client.ApiException(400, "Missing required parameter 'extraFieldParameters' when calling FieldApi->AddOrUpdateExtraFieldFieldEntityTypeKeyPost");
            }


            ZebraApp.Api.Client.RequestOptions localVarRequestOptions = new ZebraApp.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ZebraApp.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ZebraApp.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("entity_type", ZebraApp.Api.Client.ClientUtils.ParameterToString(entityType)); // path parameter
            localVarRequestOptions.PathParameters.Add("key", ZebraApp.Api.Client.ClientUtils.ParameterToString(key)); // path parameter
            localVarRequestOptions.Data = extraFieldParameters;

            localVarRequestOptions.Operation = "FieldApi.AddOrUpdateExtraFieldFieldEntityTypeKeyPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<List<ExtraField>>("/field/{entity_type}/{key}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddOrUpdateExtraFieldFieldEntityTypeKeyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Extra Field Delete an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExtraField&gt;</returns>
        public List<ExtraField> DeleteExtraFieldFieldEntityTypeKeyDelete(EntityType entityType, string key, int operationIndex = 0)
        {
            ZebraApp.Api.Client.ApiResponse<List<ExtraField>> localVarResponse = DeleteExtraFieldFieldEntityTypeKeyDeleteWithHttpInfo(entityType, key);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Extra Field Delete an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExtraField&gt;</returns>
        public ZebraApp.Api.Client.ApiResponse<List<ExtraField>> DeleteExtraFieldFieldEntityTypeKeyDeleteWithHttpInfo(EntityType entityType, string key, int operationIndex = 0)
        {
            // verify the required parameter 'key' is set
            if (key == null)
            {
                throw new ZebraApp.Api.Client.ApiException(400, "Missing required parameter 'key' when calling FieldApi->DeleteExtraFieldFieldEntityTypeKeyDelete");
            }

            ZebraApp.Api.Client.RequestOptions localVarRequestOptions = new ZebraApp.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ZebraApp.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ZebraApp.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("entity_type", ZebraApp.Api.Client.ClientUtils.ParameterToString(entityType)); // path parameter
            localVarRequestOptions.PathParameters.Add("key", ZebraApp.Api.Client.ClientUtils.ParameterToString(key)); // path parameter

            localVarRequestOptions.Operation = "FieldApi.DeleteExtraFieldFieldEntityTypeKeyDelete";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Delete<List<ExtraField>>("/field/{entity_type}/{key}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteExtraFieldFieldEntityTypeKeyDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Extra Field Delete an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExtraField&gt;</returns>
        public async System.Threading.Tasks.Task<List<ExtraField>> DeleteExtraFieldFieldEntityTypeKeyDeleteAsync(EntityType entityType, string key, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ZebraApp.Api.Client.ApiResponse<List<ExtraField>> localVarResponse = await DeleteExtraFieldFieldEntityTypeKeyDeleteWithHttpInfoAsync(entityType, key, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Extra Field Delete an extra field for a specific entity type. Returns the full list of extra fields for the entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="key"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExtraField&gt;)</returns>
        public async System.Threading.Tasks.Task<ZebraApp.Api.Client.ApiResponse<List<ExtraField>>> DeleteExtraFieldFieldEntityTypeKeyDeleteWithHttpInfoAsync(EntityType entityType, string key, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'key' is set
            if (key == null)
            {
                throw new ZebraApp.Api.Client.ApiException(400, "Missing required parameter 'key' when calling FieldApi->DeleteExtraFieldFieldEntityTypeKeyDelete");
            }


            ZebraApp.Api.Client.RequestOptions localVarRequestOptions = new ZebraApp.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ZebraApp.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ZebraApp.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("entity_type", ZebraApp.Api.Client.ClientUtils.ParameterToString(entityType)); // path parameter
            localVarRequestOptions.PathParameters.Add("key", ZebraApp.Api.Client.ClientUtils.ParameterToString(key)); // path parameter

            localVarRequestOptions.Operation = "FieldApi.DeleteExtraFieldFieldEntityTypeKeyDelete";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<List<ExtraField>>("/field/{entity_type}/{key}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteExtraFieldFieldEntityTypeKeyDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Extra Fields Get all extra fields for a specific entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExtraField&gt;</returns>
        public List<ExtraField> GetExtraFieldsFieldEntityTypeGet(EntityType entityType, int operationIndex = 0)
        {
            ZebraApp.Api.Client.ApiResponse<List<ExtraField>> localVarResponse = GetExtraFieldsFieldEntityTypeGetWithHttpInfo(entityType);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Extra Fields Get all extra fields for a specific entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExtraField&gt;</returns>
        public ZebraApp.Api.Client.ApiResponse<List<ExtraField>> GetExtraFieldsFieldEntityTypeGetWithHttpInfo(EntityType entityType, int operationIndex = 0)
        {
            ZebraApp.Api.Client.RequestOptions localVarRequestOptions = new ZebraApp.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ZebraApp.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ZebraApp.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("entity_type", ZebraApp.Api.Client.ClientUtils.ParameterToString(entityType)); // path parameter

            localVarRequestOptions.Operation = "FieldApi.GetExtraFieldsFieldEntityTypeGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ExtraField>>("/field/{entity_type}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetExtraFieldsFieldEntityTypeGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Extra Fields Get all extra fields for a specific entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExtraField&gt;</returns>
        public async System.Threading.Tasks.Task<List<ExtraField>> GetExtraFieldsFieldEntityTypeGetAsync(EntityType entityType, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ZebraApp.Api.Client.ApiResponse<List<ExtraField>> localVarResponse = await GetExtraFieldsFieldEntityTypeGetWithHttpInfoAsync(entityType, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Extra Fields Get all extra fields for a specific entity type.
        /// </summary>
        /// <exception cref="ZebraApp.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityType">Entity type this field is for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExtraField&gt;)</returns>
        public async System.Threading.Tasks.Task<ZebraApp.Api.Client.ApiResponse<List<ExtraField>>> GetExtraFieldsFieldEntityTypeGetWithHttpInfoAsync(EntityType entityType, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ZebraApp.Api.Client.RequestOptions localVarRequestOptions = new ZebraApp.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ZebraApp.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ZebraApp.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("entity_type", ZebraApp.Api.Client.ClientUtils.ParameterToString(entityType)); // path parameter

            localVarRequestOptions.Operation = "FieldApi.GetExtraFieldsFieldEntityTypeGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ExtraField>>("/field/{entity_type}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetExtraFieldsFieldEntityTypeGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
